### ISSUE TITLE
`Loader#check_missing_arguments!` is too naive

### ISSUE THREAD

**Issue by FunkyloverOne** [djezzzl/n1_loader#31]
Hello, thanks for this awesome gem! :wave: :grin: 

This line here is problematic:
https://github.com/djezzzl/n1_loader/blob/7756cf8f9506eb6307a3788928119f55c2832921/lib/n1_loader/core/loader.rb#L71

Because if I only pass the optional argument, but don't pass the required one - then `args.size >= min` is `true`, so this check passes, but shouldn't. :slightly_smiling_face:

**Comment by djezzzl** [comment]
Hi @FunkyloverOne,

> Hello, thanks for this awesome gem! wave grin

Thank you for your kind words!

> Because if I only pass the optional argument, but don't pass the required one - then args.size >= min is true, so this check passes, but shouldn't. slightly_smiling_face

You're correct! Would you like to contribute with a fix for that?

**Comment by djezzzl** [comment]
Hi @FunkyloverOne,

Thank you for pointing this out, and I'm sorry it took me so long to fix it. 

It was done here: https://github.com/djezzzl/n1_loader/pull/40.

I released it under 1.6.6.

Please let me know if that helps.

Have a great day!
